# Guide pour changer de réseau dans Portainer
# RegisFlow - Configuration réseau flexible

# ==========================================
# INSTALLATION STANDARD
# ==========================================
# 1. Déployez RegisFlow avec docker-compose up -d
# 2. Dans Portainer, allez dans Stacks > regisflow
# 3. Utilisez "Migrate" ou "Redeploy" pour changer de réseau

# ==========================================
# CHANGER DE RÉSEAU DANS PORTAINER
# ==========================================
# Option 1 : Via l'interface Portainer
# 1. Containers > regisflow-app/regisflow-db
# 2. "Disconnect" du réseau actuel
# 3. "Connect" au nouveau réseau
# 4. Redémarrer les containers

# Option 2 : Via la Stack Portainer
# 1. Stacks > votre-stack-regisflow
# 2. Editor > Modifier la section networks
# 3. Deploy the stack

# ==========================================
# RÉSEAUX COMPATIBLES PORTAINER
# ==========================================

# Réseau nginx_default (configuration actuelle)
networks:
  default:
    external: true
    name: nginx_default

# Autres réseaux existants
networks:
  default:
    external: true
    name: autre-reseau-existant

# Réseau macvlan (IP directe)
networks:
  default:
    driver: macvlan
    driver_opts:
      parent: eth0

# Réseau host (sans isolation)
# Supprimez la section networks et ajoutez :
# network_mode: host dans chaque service

# ==========================================
# PROCÉDURE MIGRATION PORTAINER
# ==========================================
# 1. Arrêter la stack dans Portainer
# 2. Modifier le docker-compose.yml si nécessaire  
# 3. Redéployer la stack
# 4. Vérifier la connectivité réseau

# ==========================================
# DÉPANNAGE RÉSEAU
# ==========================================
# Vérifier les réseaux Docker :
# docker network ls
# 
# Inspecter un réseau :
# docker network inspect nom-du-reseau
#
# Connecter manuellement un container :
# docker network connect nom-reseau nom-container