version: '3.8'

# Docker Compose pour Portainer - Construction automatique
# Ce fichier gère tout automatiquement sans configuration supplémentaire
services:
  # Base de données PostgreSQL
  regisflow-db:
    image: postgres:15-alpine
    container_name: regisflow-db
    environment:
      POSTGRES_DB: regisflow
      POSTGRES_USER: regisflow
      POSTGRES_PASSWORD: RegisFlow2024!PostgreSQL
    volumes:
      - regisflow_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U regisflow -d regisflow"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - regisflow_network

  # Application RegisFlow - Construction depuis le répertoire courant
  regisflow-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: regisflow-app:latest
    container_name: regisflow-app
    depends_on:
      regisflow-db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://regisflow:RegisFlow2024!PostgreSQL@regisflow-db:5432/regisflow
      SESSION_SECRET: RegisFlow2024SessionSecretKey1234567890ABCDEF
      TZ: Europe/Paris
      SECURE_COOKIES: false
      DATA_RETENTION_MONTHS: 19
      BACKUP_RETENTION_DAYS: 90
      MAX_BACKUP_COUNT: 20
    volumes:
      - regisflow_backup_data:/app/backups
      - regisflow_logs_data:/app/logs
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 90s
    networks:
      - regisflow_network

# Volumes avec noms uniques pour éviter les conflits
volumes:
  regisflow_postgres_data:
    driver: local
  regisflow_backup_data:
    driver: local
  regisflow_logs_data:
    driver: local

# Réseau dédié avec nom unique
networks:
  regisflow_network:
    driver: bridge
    name: regisflow_net