version: '3.8'

services:
  # Application RegisFlow seule (base de données externe)
  regisflow:
    build: .
    container_name: regisflow-app
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET:-your-super-secret-session-key-change-in-production}
      TZ: Europe/Paris
    volumes:
      - backup_data:/app/backups
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  backup_data:
    driver: local