version: '3.8'

# Configuration Stack Portainer pour RegisFlow avec build automatique
# Cette version construit l'image automatiquement depuis le code source
services:
  # Base de données PostgreSQL
  regisflow-db:
    image: postgres:15-alpine
    container_name: regisflow-db
    environment:
      POSTGRES_DB: regisflow
      POSTGRES_USER: regisflow
      POSTGRES_PASSWORD: RegisFlow2024!PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U regisflow -d regisflow"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - regisflow-net

  # Application RegisFlow - Construction automatique
  regisflow:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: regisflow-app
    depends_on:
      regisflow-db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://regisflow:RegisFlow2024!PostgreSQL@regisflow-db:5432/regisflow
      SESSION_SECRET: RegisFlow2024SessionSecretKey1234567890ABCDEF
      TZ: Europe/Paris
      SECURE_COOKIES: false
      DATA_RETENTION_MONTHS: 19
      BACKUP_RETENTION_DAYS: 90
      MAX_BACKUP_COUNT: 20
    volumes:
      - backup_data:/app/backups
      - logs_data:/app/logs
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 90s
    networks:
      - regisflow-net

# Volumes persistants
volumes:
  postgres_data:
    driver: local
  backup_data:
    driver: local
  logs_data:
    driver: local

# Réseau dédié
networks:
  regisflow-net:
    driver: bridge